name: CI Flask API

on:
  push:
    branches: [ main ]
    tags:
      - 'test-*'

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test_on_tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/test-')
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Run unit tests and coverage (tag)
        run: |
          pytest --cov=app --cov=models --cov-report=term-missing
